#!/usr/bin/env python

from docopt import docopt
from tmpl import version
from tmpl.analyze import get_template_folder, get_available_templates
from tmpl.process import copy_template

doc = """
tmpl version {}

Usage:
    tmpl [options] [<filename>]

Options:
    -t <TEMPLATE_FOLDER>, --template-folder=<TEMPLATE_FOLDER>
        Folder of available templates [default: ~/templates]
""".format(version)


if __name__ == '__main__':
    args = docopt(doc, version=version)

    template_folder = get_template_folder(args)
    if args['<filename>']:
        copy_template(args['<filename>'], template_folder)
    else:
        print(get_available_templates(template_folder))
