#!/usr/bin/env python
"""
Usage:
    tmpl [options] [<filename>]

Options:
    --version
        Show version info
"""

from docopt import docopt
from tmpl import version


if __name__ == '__main__':
    args = docopt(__doc__, version)
